name: Run tests and build images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "pipeline/**"

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pipeline

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: ./pipeline
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pipeline/pyproject.toml

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build BAML client
        run: |
          uv run baml-cli generate

      - name: Run tests
        run: |
          uv run pytest -v -k "not llm_extractors"

  build_and_push:
    name: Build and push container image
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::510900713680:role/github-actions
          aws-region: eu-west-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push pipeline image
        id: build-push
        uses: docker/build-push-action@v5
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        with:
          context: ./pipeline
          file: ./pipeline/lambda.Dockerfile
          push: true
          provenance: false
          platforms:
            - linux/amd64
          tags: |
            ${{ env.ECR_REGISTRY }}/cac-pipeline:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/cac-pipeline:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
