name: Run tests and build images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "pipeline/**"

jobs:
  test_build_push:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pipeline

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          working-directory: ./pipeline
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pipeline/pyproject.toml

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build BAML client
        run: |
          uv run baml-cli generate

      - name: Run tests
        run: |
          uv run pytest -v -k "not llm_extractors"

      - name: Build Lambda archive
        run: |
          uv export --frozen --no-dev --no-editable -o requirements.txt
          uv pip install \
            --no-installer-metadata \
            --no-compile-bytecode \
            --python-platform x86_64-manylinux_2_31 \
            --python 3.12 \
            --target packages \
            -r requirements.txt

          cd packages
          zip -q -r ../package.zip .
          cd ..

          zip -q -r package.zip ./src ./lambdas

      - name: Upload Lambda archive
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: pipeline/package.zip
